### ISSUE TITLE
[BUG] - The ipv6 domain name cannot connect to the server. I hope it can support the ipv6 domain name. Thank you.

### ISSUE THREAD

**Issue by snakwu** [wgtunnel/wgtunnel#144]
The ipv6 domain name cannot connect to the server. I hope it can support the ipv6 domain name. Thank you.

**Comment by zaneschepke** [comment]
I'll look into this!

**Comment by snakwu** [comment]
> I'll look into this!

I think it should be the address translation of the domain name. Thank you.

**Comment by goodness-from-me** [comment]
Any luck with this issue? It's really annoying - changed my ISP to provide IPv6 and set up Wireguard for IPv6 but my phone can't connect to it.
Relevant logs from the app:
```
         1718186088.926  3703  3728 I h       : Using Wg backend
         1718186088.957  3703  3728 I WireGuard/GoBackend: Bringing tunnel <tunnel> UP
         1718186088.961  3703  3764 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10331; state: ENABLED
         1718186089.200  3703  3703 E AndroidRuntime: FATAL EXCEPTION: main
         1718186089.200  3703  3703 E AndroidRuntime: Process: com.zaneschepke.wireguardautotunnel, PID: 3703
         1718186089.200  3703  3703 E AndroidRuntime: java.lang.IllegalArgumentException: Bad address
         1718186089.200  3703  3703 E AndroidRuntime: 	at android.net.VpnService.checkNonPrefixBytes(VpnService.java:479)
--------- beginning of crash
         1718186089.200  3703  3703 E AndroidRuntime: FATAL EXCEPTION: main
         1718186089.200  3703  3703 E AndroidRuntime: Process: com.zaneschepke.wireguardautotunnel, PID: 3703
         1718186089.200  3703  3703 E AndroidRuntime: java.lang.IllegalArgumentException: Bad address
         1718186089.200  3703  3703 E AndroidRuntime: 	at android.net.VpnService.checkNonPrefixBytes(VpnService.java:479)
         1718186089.200  3703  3703 E AndroidRuntime: 	at android.net.VpnService.-$$Nest$smcheckNonPrefixBytes(Unknown Source:0)
         1718186089.200  3703  3703 E AndroidRuntime: 	at android.net.VpnService$Builder.addRoute(VpnService.java:636)
         1718186089.200  3703  3703 E AndroidRuntime: 	at com.wireguard.android.backend.GoBackend.e(Unknown Source:567)
         1718186089.200  3703  3703 E AndroidRuntime: 	at com.wireguard.android.backend.GoBackend.c(Unknown Source:37)
         1718186089.200  3703  3703 E AndroidRuntime: 	at a4.h.a(Unknown Source:336)
         1718186089.200  3703  3703 E AndroidRuntime: 	at a4.e.s(Unknown Source:85)
         1718186089.200  3703  3703 E AndroidRuntime: 	at I4.a.q(Unknown Source:8)
         1718186089.200  3703  3703 E AndroidRuntime: 	at b5.F.run(Unknown Source:114)
         1718186089.200  3703  3703 E AndroidRuntime: 	at b5.l0.run(Unknown Source:146)
         1718186089.200  3703  3703 E AndroidRuntime: 	at i5.j.run(Unknown Source:2)
         1718186089.200  3703  3703 E AndroidRuntime: 	at i5.a.run(Unknown Source:91)
         1718186089.200  3703  3703 E AndroidRuntime: 	Suppressed: g5.g: [m0{Cancelling}@e9d751d, Dispatchers.Main.immediate]
```

**Comment by snakwu** [comment]
@zaneschepke 请问关于这个问题，有进展吗？

**Comment by snakwu** [comment]
@zaneschepke Is there any progress? Thank you

**Comment by devastgh** [comment]
It works perfectly on my pixel 6. I'm using a domain for the endpoint address, and it has both a and aaa records. My mobile isp provides ipv6 on the network, and my phone is connecting to the wg server over ipv6.

![kép](https://github.com/user-attachments/assets/2c7a2188-45ba-45fe-bbcd-761e742fc005)

**Comment by snakwu** [comment]
> It works perfectly on my pixel 6. I'm using a domain for the endpoint address, and it has both a and aaa records. My mobile isp provides ipv6 on the network, and my phone is connecting to the wg server over ipv6.
> 
> ![kép](https://private-user-images.githubusercontent.com/25620318/368170084-2c7a2188-45ba-45fe-bbcd-761e742fc005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODMwNjUsIm5iZiI6MTcyNjU4Mjc2NSwicGF0aCI6Ii8yNTYyMDMxOC8zNjgxNzAwODQtMmM3YTIxODgtNDViYS00NWZlLWJiY2QtNzYxZTc0MmZjMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YjZiOGYxYmI3ZDk1MDU2NThmYjE1MGZjMWFhYzUxOGMyMGQ1OTllYjMyNjA1ZDlmZmJlOTQzYzU3NDk5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.boYHPBSnjRL1S9JEMLNu8ObOROuWhqLqQfBmJdldVSQ)
Hi, I'd like to ask if you're building the server with the same setup. I'm using this project
https://github.com/freifunkMUC/wg-access-server

**Comment by devastgh** [comment]
> Hi, I'd like to ask if you're building the server with the same setup. I'm using this project
 > https://github.com/freifunkMUC/wg-access-server

I'm using openwrt and linux as the server side, but it really shouldn't matter. Make sure that your domain, in your example the "xxx.snakwu.com:51820" has an AAA record with the ipv6 address of your server. The crash probably happens when you input an ipv6 ip address into the endpoint field, but i haven't tried that since i'm using a domain address in there.

**Comment by snakwu** [comment]
> > Hi, I'd like to ask if you're building the server with the same setup. I'm using this project
> > https://github.com/freifunkMUC/wg-access-server
> 
> I'm using openwrt and linux as the server side, but it really shouldn't matter. Make sure that your domain, in your example the "xxx.snakwu.com:51820" has an AAAA record with the ipv6 ip address of your server. The crash probably happens when you input an ipv6 ip address into the endpoint field, but i haven't tried that since i'm using a domain address in there.
When I use a domain including aaa, for example: xxx.xxxx.com: 5182 is unable to connect, if using an IPv6 address, for example: "[240e: 3b2: xxx: xxx:: 55]: 51820 In this way, it is possible to connect, of course, my domain name contains the AAAA record.

**Comment by snakwu** [comment]
> > Hi, I'd like to ask if you're building the server with the same setup. I'm using this project
> > https://github.com/freifunkMUC/wg-access-server
> 
> I'm using openwrt and linux as the server side, but it really shouldn't matter. Make sure that your domain, in your example the "xxx.snakwu.com:51820" has an AAAA record with the ipv6 ip address of your server. The crash probably happens when you input an ipv6 ip address into the endpoint field, but i haven't tried that since i'm using a domain address in there.

When I use a domain including AAAA, for example: xxx.xxxx.com: 5182 is unable to connect, if using an IPv6 address, for example: "[240e: 3b2: xxx: xxx:: 55]: 51820 In this way, it is possible to connect, of course, my domain name contains the AAAA record.

**Comment by snakwu** [comment]
If you use a domain name, you can't connect
![Screenshot_20240918_093357_WG Tunnel](https://github.com/user-attachments/assets/d14f2878-d8da-4197-a1a7-0e44f92c2369)


If you directly use the ip address is a normal connection
![Screenshot_20240918_093427_WG Tunnel](https://github.com/user-attachments/assets/a03cc279-5184-422f-8e95-4a7a45f652f8)

**Comment by devastgh** [comment]
> @devastgh If you use a domain name, you can't connect !

I managed to reproduce this. If the endpoint address does have an AAAA record, but does not have an A record, then the tunnel will fail. If it has both A and AAAA records (dual stack ipv4 + ipv6), then ipv6 will be usable.

In the logs:

`2024-09-18T06:40:35.000000527Z 20144 3271 WARNING WireGuard/GoBackend: message= DNS host "[xxxxxx.duckdns.org](http://xxxxxx.duckdns.org/)" failed to resolve; trying again`

**Comment by snakwu** [comment]
> > @devastgh If you use a domain name, you can't connect !
> 
> I managed to reproduce this. If the endpoint address does have an AAAA record, but does not have an A record, then the tunnel will fail. If it has both A and AAAA records (dual stack ipv4 + ipv6), then ipv6 will be usable.
> 
> In the logs:
> 
> `2024-09-18T06:40:35.000000527Z 20144 3271 WARNING WireGuard/GoBackend: message= DNS host "[xxxxxx.duckdns.org](http://xxxxxx.duckdns.org/)" failed to resolve; trying again`

I feel you are using the IPv4 address connection, my domain name has A and AAAA at the same time, record, can only connect from A record

**Comment by devastgh** [comment]
> > > @devastgh If you use a domain name, you can't connect !
> > 
> > 
> > I managed to reproduce this. If the endpoint address does have an AAAA record, but does not have an A record, then the tunnel will fail. If it has both A and AAAA records (dual stack ipv4 + ipv6), then ipv6 will be usable.
> > In the logs:
> > `2024-09-18T06:40:35.000000527Z 20144 3271 WARNING WireGuard/GoBackend: message= DNS host "[xxxxxx.duckdns.org](http://xxxxxx.duckdns.org/)" failed to resolve; trying again`
> 
> I feel you are using the IPv4 address connection, my domain name has A and AAAA at the same time, record, can only connect from A record

I found out my tests were flawed, as my phone did not have ipv6 connection at the time of the testing, hence why it failed to resolve it.
So i cannot reproduce this. Are you sure, that the DNS servers set on your phone do give back ipv6 records ? Maybe try it with setting dns manually to 1.1.1.1

**Comment by snakwu** [comment]
> > > > @devastgh If you use a domain name, you can't connect !
> > > 
> > > 
> > > I managed to reproduce this. If the endpoint address does have an AAAA record, but does not have an A record, then the tunnel will fail. If it has both A and AAAA records (dual stack ipv4 + ipv6), then ipv6 will be usable.
> > > In the logs:
> > > `2024-09-18T06:40:35.000000527Z 20144 3271 WARNING WireGuard/GoBackend: message= DNS host "[xxxxxx.duckdns.org](http://xxxxxx.duckdns.org/)" failed to resolve; trying again`
> > 
> > 
> > I feel you are using the IPv4 address connection, my domain name has A and AAAA at the same time, record, can only connect from A record
> 
> I found out my tests were flawed, as my phone did not have ipv6 connection at the time of the testing, hence why it failed to resolve it. So i cannot reproduce this. Are you sure, that the DNS servers set on your phone do give back ipv6 records ? Maybe try it with setting dns manually to 1.1.1.1

![Screenshot_20240918_165720_Edge](https://github.com/user-attachments/assets/e3615497-c6eb-4988-b085-9e823459a5c1)
Determine that the ipv6 of the network is

**Comment by snakwu** [comment]
@zaneschepke Hello, is there any update on the IPv6 issue? Hope to fix it, thank you.

**Comment by zaneschepke** [comment]
> @zaneschepke Hello, is there any update on the IPv6 issue? Hope to fix it, thank you.

No update on this one, but I'll try to prioritize it.

**Comment by snakwu** [comment]
Thank you and look forward to your good news😊

**Comment by zaneschepke** [comment]
I was able to reproduce this when trying to connect to my wireguard server configured for ipv6 behind CGNAT. 

The issue is wireguard is coded to prefer ipv4 (which is supposed to prevent dns64 and ipv6 NAT issues), but this obviously causes these connection issues with ipv6 domains. 

So I think the best fix for this is to add a toggle to allow the user to turn of wireguard's ipv4 preference, but have this preference enabled by default for backwards compatibility. When i tested this, Android properly preferred ipv6 and it fixed this issue. 

I only have this fixed for userspace mode. Do we know if this impacts kernel mode as well (kernel mode resolves domains differently)?

**Comment by snakwu** [comment]
@zaneschepke As far as I know, kernel mode has the same problem

**Comment by zaneschepke** [comment]
Hello! I've made a test version where I have added support to turn off wireguard's default ipv4 preference. Please give this a try and let me know if it solves this issue: https://github.com/zaneschepke/wgtunnel/releases/tag/multitunnel-ipv6-test

**Comment by snakwu** [comment]
All right, let me test it.

**Comment by zaneschepke** [comment]
> I quickly tested the beta release and it works as expected. Thank you! With the default disabled "IPv4 hostname resolution" is IPv6 connectivity finally preferred. When enabling the toggle, it behaves like before, preferring IPv4. For me this bug seems solved.
> 
> IMO there is no need for an additional option for IPv4 preference. We are in 2025, and if your network has a broken IPv6 connection you will face other issues as well, and you should fix the IPv6 setup sooner than later.

I would like to leave the setting for backwards compatibility purposes. Also, the reason WG decided on this default in the first place was to prevent IPv6 NAT issues so it would be good to allow users to turn this on if they encounter issues.

**Comment by snakwu** [comment]
> > I quickly tested the beta release and it works as expected. Thank you! With the default disabled "IPv4 hostname resolution" is IPv6 connectivity finally preferred. When enabling the toggle, it behaves like before, preferring IPv4. For me this bug seems solved.
> > IMO there is no need for an additional option for IPv4 preference. We are in 2025, and if your network has a broken IPv6 connection you will face other issues as well, and you should fix the IPv6 setup sooner than later.
> 
> I would like to leave the setting for backwards compatibility purposes. Also, the reason WG decided on this default in the first place was to prevent IPv6 NAT issues so it would be good to allow users to turn this on if they encounter issues.

Test only ipv6 domain name, can connect normally, very grateful.

**Comment by snakwu** [comment]
@zaneschepke After a period of testing, if you use ipv6 connection, it will be unstable, and you often have to retry many times before you can connect.

**Comment by zaneschepke** [comment]
> [@zaneschepke](https://github.com/zaneschepke) After a period of testing, if you use ipv6 connection, it will be unstable, and you often have to retry many times before you can connectThere is a water supply outage.

Hello! Is this true for the latest version 3.7.2? There were some regressions in the past few versions since this feature released that could be causing these types of issues.

**Comment by snakwu** [comment]
> > [@zaneschepke](https://github.com/zaneschepke) After a period of testing, if you use ipv6 connection, it will be unstable, and you often have to retry many times before you can connectThere is a water supply outage.
> 
> Hello! Is this true for the latest version 3.7.2? There were some regressions in the past few versions since this feature released that could be causing these types of issues.

3.7.2, the current ipv6 normal, but the notification bar shortcut switch, open the connection is very slow.

**Comment by zaneschepke** [comment]
I think this one is completed as of 3.8.3. I'll mark this one as closed for now. 

Let me know if there are still issues and we can reopen.

**Comment by snakwu** [comment]
> I think this one is completed as of 3.8.3. I'll mark this one as closed for now.
> 
> Let me know if there are still issues and we can reopen.

I don't know if I can get an update on Google Play, thanks!

**Comment by zaneschepke** [comment]
> > I think this one is completed as of 3.8.3. I'll mark this one as closed for now.
> > Let me know if there are still issues and we can reopen.
> 
> I don't know if I can get an update on Google Play, thanks!

I have been being denied from Google play for the past versions. I think I fixed what they were mad about so hopefully this version is approved. It is in review now.

**Comment by snakwu** [comment]
> > > I think this one is completed as of 3.8.3. I'll mark this one as closed for now.
> > > Let me know if there are still issues and we can reopen.
> > 
> > 
> > I don't know if I can get an update on Google Play, thanks!
> 
> I have been being denied from Google play for the past versions. I think I fixed what they were mad about so hopefully this version is approved. It is in review now.

It has been updated manually, and now there is a detection update function in the program, so google play doesn't matter, thanks again!

**Comment by e-tho** [comment]
This issue is still present in v4.1.8. I can connect to the server using my public IPv6 address as an endpoint, but the connection fails when using my DDNS hostname.
I've thoroughly reviewed and tested my server, DDNS, and smartphone DNS configurations, and everything checks out. The issue appears to stem from the client.

**Comment by zaneschepke** [comment]
> This issue is still present in v4.1.8. I can connect to the server using my public IPv6 address as an endpoint, but the connection fails when using my DDNS hostname.
> I've thoroughly reviewed and tested my server, DDNS, and smartphone DNS configurations, and everything checks out. The issue appears to stem from the client.

Hey, can you ping or email me any logs of this? Do you have prefer IPv6 enabled? Are you using DoH? Does it error with a DNS error when you start the tunnel? Are you in standard VPN mode?

**Comment by devastgh** [comment]
When the endpoint is dual stack (has both A and AAAA records), prefer ipv6 works properly for me. I can't test with an endpoint that only has AAAA record.

**Comment by e-tho** [comment]
Oddly, when I use my domain, my public IPv6 address shows up correctly as the endpoint on the 'Tunnels' page, which suggests it's resolving properly. However, the connection fails when I'm on mobile data, even though it works fine when I'm on the local network (the same one as the server).

On the other hand, if I manually set my public IPv6 address as the endpoint, the connection works as expected whether I'm on the local network or mobile data.

My DDNS is set up as dual-stack, and I've already tried setting it to IPv6-only with no luck. 'Prefer IPv6 peer resolution' did not help either. I use system DNS on GrapheneOS so 'Private DNS' is likely using DoT, not DoH. No DNS error when I start the tunnel and I'm in standard VPN mode.

**Comment by zaneschepke** [comment]
> Oddly, when I use my domain, my public IPv6 address shows up correctly as the endpoint on the 'Tunnels' page, which suggests it's resolving properly. However, the connection fails when I'm on mobile data, even though it works fine when I'm on the local network (the same one as the server).
> 
> On the other hand, if I manually set my public IPv6 address as the endpoint, the connection works as expected whether I'm on the local network or mobile data.
> 
> My DDNS is set up as dual-stack, and I've already tried setting it to IPv6-only with no luck. 'Prefer IPv6 peer resolution' did not help either. I use system DNS on GrapheneOS so 'Private DNS' is likely using DoT, not DoH. No DNS error when I start the tunnel and I'm in standard VPN mode.

It sounds like an issue with your mobile provider's DNS. Try change the DNS settings in the app from system to DoH and see if that fixes the issue.

**Comment by e-tho** [comment]
> Try change the DNS settings in the app from system to DoH and see if that fixes the issue.

DoH didn't help. I've verified DNS resolution on both networks, both correctly resolve to the same IPv6 address. Mobile uses my carrier's DNS, local uses my Pi-hole.

Could there be different endpoint values for display and connection? One correctly resolved and the other stale?

The fact that manually setting the IPv6 address works confirms the IPv6 connectivity is fine.

**Comment by e-tho** [comment]
My bad, my DDNS update script had two issues:
1. It was making separate IPv4 and IPv6 requests that overwrote each other instead of updating both atomically (causing the A record to disappear)
2. The IPv6 detection was picking up the temporary privacy address instead of the stable one

I don't know which one or if both were causing this, but after fixing both, I can finally connect to the VPN with mobile data.

**Comment by zaneschepke** [comment]
> My bad, my DDNS update script had two issues:
> 
> 1. It was making separate IPv4 and IPv6 requests that overwrote each other instead of updating both atomically (causing the A record to disappear)
> 2. The IPv6 detection was picking up the temporary privacy address instead of the stable one
> 
> I don't know which one or if both were causing this, but after fixing both, I can finally connect to the VPN with mobile data.

No worries! Glad you found the fix!
