### ISSUE TITLE
[BUG] - Toggle icon shows tunnel as disconnected when using kernel module

### ISSUE THREAD

**Issue by gardar** [wgtunnel/wgtunnel#905]
**Describe the bug**
When using the kernel module method, the toggle to connect to tunnels always shows as toggled off. Clicking it gives Tunnel already running in the logs. This makes it impossible to disconnect from a tunnel, since the toggle always tries to activate the tunnel instead of deactivating an already running one.

It doesn’t matter if I enable the tunnel manually or with the auto-tunnel option—the icon always stays toggled off.

If I use the userspace backend instead of the kernel module, the toggle works as expected.

I only noticed this issue recently; I’m not sure if it’s caused by a recent app update or by the latest OTA.

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- Android Version: 16 (BP2A.250805.005)
- App Version 3.9.5
- Backend: [e.g. Kernel, Userspace]

**To Reproduce**

1. Enable the kernel backend
2. Click on a tunnel
3. ????
4. Profit

**Expected behavior**
The connection to represent the true state of the tunnel

**Screenshots (Only if necessary)**

**Additional context**

**Comment by olmet** [comment]
Here is the same problem.

Smartphone (please complete the following information):

    Device: Pixel 3a
    Android Version: 13
    App Version 3.9.5


    The previous version 3.9.4 works.

**Comment by AnalogKid96** [comment]
I had the same issue with the kernel backend. It seems to be fixed in the latest nightly. I think this commit fixed it.
 https://github.com/wgtunnel/wgtunnel/commit/82b39695de354974e52bb42a16783bcf21274d40

**Comment by gardar** [comment]
Yeah seems to be fixed for me as well!
One thing worth mentioning for anyone switching over to the nightly version is that you need to grant VPN permissions to the app before attempting to use the kernel backend... The app kept crashing as soon as I enabled a tunnel using the kernel backend, what fixed it for me was to switch over to the VPN backend and accepting the VPN permissions request and then switching back to the kernel one.

**Comment by zaneschepke** [comment]
> Yeah seems to be fixed for me as well! One thing worth mentioning for anyone switching over to the nightly version is that you need to grant VPN permissions to the app before attempting to use the kernel backend... The app kept crashing as soon as I enabled a tunnel using the kernel backend, what fixed it for me was to switch over to the VPN backend and accepting the VPN permissions request and then switching back to the kernel one.

Hmm. This is a bug then. This should not be necessary. I'll look into this and we can track this bug fix under this issue (I'll keep this open for now).

But it is good to hear the original issue is fixed! Thank you both for letting us know.

**Comment by zaneschepke** [comment]
Actually, it seems this issue is being tracked in #935 

I'll close this one out and we cant track this crash/security exception issue there.

**Comment by diegantobass** [comment]
Hello,
Sorry to necro this thread but I still have the exact issue described.

    Device: Unihertz Titan 2
    Android Version: 15 (AP3A.240905.015.A2)
    App Version 4.2.2
    Backend: Kernel

On boot, things go smooth, I launch a tunnel, it starts. A couple of hours later, when I check back, the toggle for the tunnel is off. But my IP is still that of the tunnel. So I can"t turn it off.

Thanks
